; This script automatically creates Google Accounts (Smoke Test for Google's Account Creating functionality)
; Author Sylvester L. 04/29/2019
; Tested on version 74.0.3729.108 of Chrome desktop browser, other versions added as tested
; Precondition for running script fluently:
;  1. - fairly good internet connection that doesn't exceed preprogrammed waiting times
;  2. - verification code is sent in a timeframe that doesn't exceed viewers' patience levels
; (Store waiting times in variables and use them instead to save time)
;~ $1s = Sleep (1000)
;~ $2s = Sleep (2000)
;~ $3s = Sleep (3000)
;~ $4s = Sleep (4000)
;~ $5s = Sleep (5000)
;~ $6s = Sleep (6000)
;~ $7s = Sleep (7000)
;~ $8s = Sleep (8000)
;~ $9s = Sleep (9000)
;~ $10s = Sleep (10000); - just discovered commenting code with selecting them and/or pressing - key
; The above definitions would work but the script waits the sum of the above seconds, I suspect some other ways of defining them
; After every step, wait for window to load if needed and wait as many seconds as needed for demonstrative purposes
; (As a procedural programming menthodology, write a simple script first, then randomize and multiply, content must be stored in a text document)
; (Start with 2 times or enter as many as you want and exit the script manually when needed)

; Open Chrome in incognito maximized
Run ("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe -incognito", "", @SW_MAXIMIZE)
WinWaitActive ("[CLASS:Chrome_WidgetWin_1]")
Sleep (3000)
; Open Google page
Send ("google.com")
Sleep (1000)
Send ("{ENTER}")
;~ ; Wait for window to be active
;~ WinWaitActive ("[CLASS:Chrome_WidgetWin_1]"); not necessary
; Wait a certain amount of time for page to be loaded
Sleep (5000)
;~ ; 19 Tab
;~ ;Send ("{TAB 19}")
;~ ; Enter to Google Services
;~ ; Changed to click Google Services directly because if Therms Change Memento appears than TAB numbers change too
;~ ;  and rather click directly (1 step), than proceed by pixel colour of Memento Review button (~5 steps) - which is also relative to screen resolution
;~ MouseClick ("", 1202, 101)
; Discovered later that Shift+Tab progresses backwords, so only 2 of them needed to get the job done
Send ("+{TAB 2}")
Sleep (1000)
; Enter Google Services
Send ("{ENTER}")

; Enter Google Account
Sleep (3000)
Send ("{ENTER}")
; 14 Tab-s
Sleep (3000)
Send ("{TAB 14}")
; Enter to Create New Google Account
Sleep (1000)
Send ("{ENTER}")
; Write First Name (Randomize it later)
$firstName = "Tester"
Sleep (3000)
Send ($firstName)
; Tab
Sleep (1000)
Send ("{TAB}")
; Write Last Name (Randomize it later)
$lastName = "Testing"
Sleep (1000)
Send ($lastName)
; Username gets generated by Google in at most 5 seconds as tested (IF it gets generated, so it would be better with PixelGetColor)

; Copy username to a text document
Sleep (15000)
Send ("{TAB}")
Sleep (1000)
Send ("^c")
Sleep (1000)
Run ("notepad.exe")
WinWaitActive ("[CLASS:Notepad]")
Sleep (1000)
Send ("^v")
Sleep (2000)
WinActivate ("[CLASS:Chrome_WidgetWin_1]"); new command instead of Alt+Tab - which doesn't guarantee activation of desired window
; Activates only the window, but Tab doesn't progress activating any input box
;~ WinSetOnTop ("[CLASS:Chrome_WidgetWin_1]")
; This doesn't work at all
;~ WinActive ("[CLASS:Chrome_WidgetWin_1]")
; This doesn't work either so try a click
;~ ControlClick ("[CLASS:Chrome_WidgetWin_1]", "", "Intermediate D3D Window1")
; New command instead of MouseClick - which moves the mouse visibly, that's not really needed
; - but that's not working either so use MouseClick on a most compatible place with other screen resolutions
Sleep (1000)
MouseClick ("", 10, 400)
Sleep (1000)

; Copy password to the same text document (It would be better to copy password from Chrome as final source and not from variable)
; 5 Tab-s to activate password input box because it starts progressing from the first field again
Send ("{TAB 5}")
; Write and confirm password - Should be 9 characters with number and symbol (Randomize it later)
$password = "testers1@"
Sleep (1000)
Send ($password)
Sleep (1000)
; Tab
Send ("{TAB}")
Sleep (1000)
; Confirm Password
Send ($password)
Sleep (1000)
; (It would be better to copy to Google Sheets as it manages versions with the same filename, but it can be worked around in Notepad too)
WinActivate ("[CLASS:Notepad]"); - WinActivate works like charm in Notepad
Sleep (1000)
Send ("{SPACE}")
Send ($password)
Sleep (1000)
; Get back to Chrome
WinActivate ("[CLASS:Chrome_WidgetWin_1]")
Sleep (1000)
MouseClick ("", 10, 400)
Sleep (1000)

; Enter Phone number and verification code through input boxes
; 8 Tab-s
Send ("{TAB 8}")
Sleep (1000)
; Enter to Next Window
Send ("{ENTER}")
Sleep (3000)
; Copy from input box the phone number
$phoneNumber = InputBox ("AutoIT:", "Please enter phone no. at hand!")
Send ($phoneNumber)
Sleep (1000)
; Enter to Next Page
Send ("{ENTER}")
Sleep (1000)
; Input box (Think about other possibilities to get verification code, for example phone app that sends it automatically through email & get it from there)
$verifCode = InputBox ("AutoIT:", "Please enter Verification code!")
Sleep (1000)
; Copy from input box the verification code
Send ($verifCode)
Sleep (1000)
; Enter to Verify
Send ("{ENTER}")
Sleep (3000)

; Finalize Google account creation
; Ctrl+A and Delete to erase phone number
Send ("^a")
Sleep (1000)
Send ("{DEL}")
Sleep (1000)
; 2 Tab-s
Send ("{TAB 2}")
Sleep (1000)
; Write Month of birth (Randomize if you want)
Send ("ja")
Sleep (1000)
; Tab
Send ("{TAB}")
Sleep (1000)
; Write Day (Randomize if you want)
Send ("01")
Sleep (1000)
; Tab
Send ("{TAB}")
Sleep (1000)
; Write Year (Randomize if you want)
Send ("2000")
Sleep (1000)
; Tab
Send ("{TAB}")
Sleep (1000)
; Write Gender (Randomize if you want)
Send ("r")
Sleep (1000)
; 2 Tab-s
Send ("{TAB 2}")
Sleep (1000)
; Enter to Next page
Send ("{ENTER}")
Sleep (3000)

; Accept Therms & Data processing
; The modification in number of active (clickable) text in this page can alter the result
; 6 Tab-s
Send ("{TAB 6}")
Sleep (1000)
; Space to check Agree Therms
Send ("{SPACE}")
Sleep (1000)
; Tab
Send ("{TAB}")
Sleep (1000)
; Space to check Agree Processing Data
Send ("{SPACE}")
Sleep (1000)
; 2 Tab-s
Send ("{TAB 2}")
Sleep (1000)
; Enter to Create Account
Send ("{ENTER}")
Sleep (5000)
; Alt+F4 to close window
Send ("!{F4}")
Sleep (2000)

; Save opened txt with user and pass to the desktop:
; Activate Notepad window - if by accident it's not activated already by closing Chrome, or other windows are open
WinActivate ("[CLASS:Notepad]")
Sleep (1000)
; Save as with Alt + F + A
Send ("!fa")
Sleep (1000)
; 5 tab-s backwards
Send ("+{TAB 5}")
Sleep (1000)
; Enter to write adress
Send ("{ENTER}")
Sleep (1000)
; Only write desktop
Send ("desktop")
Sleep (1000)
; Enter to save adress
Send ("{ENTER}")
Sleep (1000)
; 5 tabs
Send ("{TAB 5}")
Sleep (1000)
; Jump to beginning of title with Home
Send ("{HOME}")
Sleep (1000)
; Delete *
Send ("{DEL}")
Sleep (1000)
; Write title: GoogleAccount
Send ("GoogleAccount")
Sleep (1000)
; Save with Alt + S
Send ("!s")
Sleep (2000)
; Close Notepad with Alt + F4
Send ("!{F4}")
; Close Script
Exit
; Finished
